### PR TITLE
New viral symptoms to vary the pool a bit

### PR DESCRIPTION
**Pull request by Auron1213**
2x plasma virus traits, one beneficial and one lethal.
Spaceskin (Biosuit) produces ludicrous amounts of Leprozine (?) which will aide in spacewalking with no clothes.
Hothead is a highly lethal plasma trait that manifests in extremely high temperatures with a very low related rate of occurrence. In testing this, once it occurred, it put me into crit within 30 seconds.
In exchange, it highly limits transmission.

### CODE REVIEW

**Comment by MisterStaub** [comment]
We dont necessarily need a spacewalking virus, since virology already has several symptons that make it much easier to survive out there, like self respiration or the classic Toxic Comp/Filter combo.

The hothead one however is a cool idea, virology needs some more lethal stuff that isnt useless.

**Comment by InfiniKraut** [comment]
Spaceskin seems like it could really fuck over balance, so we'd need some discussion about that one

Hothead I can merge. Might have to change the symptom-text a little though

**Comment by Auron1213** [comment]
Feel free to modify both.
The biosuit is a lot less OP then what you're guessing. If you set the leporazine (?) generation to 60, spacewalking time is doubled with no suit and almost sustainable with tox comp + filter, but not as effective as a suit itself. I buffed it before committing for the sake of narrowing down the traits needed just for spacewalk, but it wasn't even very effective.
I feel that four unique plasma traits (tox comp + filter, self resp, biosuit) is a fair pool, especially since very few people use viro at all, and would take advantage of these.

Please suggest traits, in-thread or here. ss13 coding is suprisingly easy, but I'm having a hard time coming up with something fun.
If you can't think of anything, I'll be tinkering with it some on sunday.

**Comment by Auron1213** [comment]
Just got done adding Anti-vitiligo, a high-potency virus with traits of Voice Change (but not random, which is slightly less useful, since you can't self-infect to gain access) and Vitiligo, but blacker.

**Comment by Auron1213** [comment]
And there's mlady.dm, comments inside.

**Comment by InfiniKraut** [comment]
Alright, don't know if you saw the discussion in the thread, but we might switch over to the newest /tg/ revision. Don't know if the virology system changed, so you might have to rework the symptoms, I'll update you in about 15 hours

**Comment by Auron1213** [comment]
New /tg/ should be the same, though if you frankencoded in new viro I'd have to redo them, yeah.
Thanks for the update.

**Pull request closed without merging**
