### PR TITLE
Metastation

### PR DESCRIPTION
**Pull request by ghost**
Fixes the missing wooden tables and chairs.

### CODE REVIEW

**Comment by InfiniKraut** [comment]
Awesome, thanks for helping out. Could you just add a more detailed description where the stuff (as in room names or coordinates) was changed?

**Comment by ghost** [comment]
Yeah, sure.

-Changed an area in the sec arrivals checkpoint that was marked as space.
-Tables in vacant office
-Tables in the chapel (Chaplain's office and the church itself)
-Tables in the library (Office, quiet room and some more)
-Tables in the corporate display room
-Comfy chairs in the captain's office, they were missing the model and were not showing up.
-Tables in the maintenance bar.
-Poker tables in the bar

While reviewing the map I noticed I missed some missing tables in the theatre stage.

**Comment by ghost** [comment]
That 3rd commit should fix the tables in the theatre.

**Comment by InfiniKraut** [comment]
Coderbro Just alerted me that git merge doesn't sometimes deal with dmm files properly, could you upload (or md5sum) your map file somewhere so I can compare them?

**Comment by ghost** [comment]
a.pomf.se/cpuqdj.dmm

**Comment by InfiniKraut** [comment]
4f8db9fd6213eb87f2261ab01d142d33  cpuqdj.dmm
4f8db9fd6213eb87f2261ab01d142d33  _maps/map_files/MetaStation/MetaStation.v39k.dmm

Alright, worked out fine, server will be recompiled when there are less players online

**Pull request merged**
